<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kaspar Rufibach">
<meta name="dcterms.date" content="2023-04-02">

<title>Why do we use group-sequential designs?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="GSD_files/libs/clipboard/clipboard.min.js"></script>
<script src="GSD_files/libs/quarto-html/quarto.js"></script>
<script src="GSD_files/libs/quarto-html/popper.min.js"></script>
<script src="GSD_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GSD_files/libs/quarto-html/anchor.min.js"></script>
<link href="GSD_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GSD_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GSD_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GSD_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GSD_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Why do we use group-sequential designs?</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kaspar Rufibach </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 2, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="purpose-of-this-document" class="level1">
<h1>Purpose of this document</h1>
<p>This R markdown file accompanies this <a href="https://www.linkedin.com/pulse/why-do-we-interim-analyses-clinical-trials-kaspar-rufibach/?trackingId=sHnxC65nS7enuyAXRU5exQ%3D%3D">linkedin article</a> and provides the code to reproduce all computations. It heavily borrows from code within the <a href="http://www.rpact.org">rpact project</a>. Find the code on <a href="https://github.com/numbersman77/twitter.git">github</a>.</p>
<p>A much more comprehensive description is available in this <a href="https://vignettes.rpact.org/html/rpact_survival_examples.html#8_Sample_size_calculation_for_trials_with_interim_analyses">rpact vignette</a>.</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --------------------------------------------------------------</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># packages</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># --------------------------------------------------------------</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>packs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"rpact"</span>, <span class="st">"reporttools"</span>)    </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(packs)){<span class="fu">library</span>(packs[i], <span class="at">character.only =</span> <span class="cn">TRUE</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Lade nötiges Paket: xtable</code></pre>
</div>
</div>
</section>
<section id="code" class="level1">
<h1>Code</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --------------------------------------------------------------</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># trial basics</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># --------------------------------------------------------------</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fl">0.2</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># effect size and medians</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="dv">60</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>hr <span class="ot">&lt;-</span> <span class="fl">0.75</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> m1 <span class="sc">/</span> hr</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># required events for single-stage design, i.e. without interim</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>nevent <span class="ot">&lt;-</span> <span class="fu">getSampleSizeSurvival</span>(<span class="at">hazardRatio =</span> hr, <span class="at">sided =</span> <span class="dv">2</span>, <span class="at">alpha =</span> alpha, <span class="at">beta =</span> beta)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>nevent <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(nevent<span class="sc">$</span>maxNumberOfEvents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>So for a single stage design we need 380 events <strong>in any case</strong>, i.e.&nbsp;even if the effect is much smaller or larger than what we assume for powering (hazard ratio = 0.75).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># information fractions after which to perform interim looks</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>info <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">0.66</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now generate a design where you add a futility interim after 30% of events and an interim for efficacy after 66% of events. At the futility interim, the trial will be stopped if the hazard ratio is below 1 and for effiacy we use an O’Brian-Fleming type <span class="math inline">\(\alpha\)</span>-spending function (or rather the Lan-DeMets approximation to it).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OBF design without initial interim at 30% (to get cumulative alpha-spending function for these visits)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>design1 <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">sided =</span> <span class="dv">1</span>, <span class="at">alpha =</span> alpha <span class="sc">/</span> <span class="dv">2</span>, <span class="at">beta =</span> beta, </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">informationRates =</span> info[<span class="sc">-</span><span class="dv">1</span>],</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">typeOfDesign =</span> <span class="st">"asOF"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># now spend very little alpha at first interim --&gt; interim stopping not an option</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># -6 codifies "no futility" at the 2nd interim</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">futilityBounds =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">6</span>), <span class="at">bindingFutility =</span> <span class="cn">FALSE</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">informationRates =</span> info, <span class="at">typeOfDesign =</span> <span class="st">"asUser"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">userAlphaSpending =</span> <span class="fu">c</span>(<span class="fl">0.0000001</span>, design1<span class="sc">$</span>alphaSpent))</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>samplesize <span class="ot">&lt;-</span> <span class="fu">getSampleSizeSurvival</span>(<span class="at">design =</span> design, <span class="at">lambda2 =</span> <span class="fu">log</span>(<span class="dv">2</span>) <span class="sc">/</span> m1, <span class="at">hazardRatio =</span> hr,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">dropoutRate1 =</span> <span class="fl">0.025</span>, <span class="at">dropoutRate2 =</span> <span class="fl">0.025</span>, <span class="at">dropoutTime =</span> <span class="dv">12</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">accrualTime =</span> <span class="dv">0</span>, <span class="at">accrualIntensity =</span> <span class="dv">42</span>, <span class="at">maxNumberOfSubjects =</span> <span class="dv">1200</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>samplesize</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Design plan parameters and output for survival data:

Design parameters:
  Information rates                            : 0.300, 0.660, 1.000 
  Critical values                              : 5.199, 2.524, 1.992 
  Futility bounds (non-binding)                : 0.000, -Inf 
  Cumulative alpha spending                    : 0.0000001, 0.0057983, 0.0250000 
  Local one-sided significance levels          : 0.0000001, 0.0057983, 0.0232097 
  Significance level                           : 0.0250 
  Type II error rate                           : 0.2000 
  Test                                         : one-sided 

User defined parameters:
  lambda(2)                                    : 0.0116 
  Hazard ratio                                 : 0.750 
  Maximum number of subjects                   : 1200 
  Accrual time                                 : 28.57 
  Accrual intensity                            : 42.0 
  Drop-out rate (1)                            : 0.025 
  Drop-out rate (2)                            : 0.025 

Default parameters:
  Theta H0                                     : 1 
  Type of computation                          : Schoenfeld 
  Planned allocation ratio                     : 1 
  kappa                                        : 1 
  Piecewise survival times                     : 0.00 
  Drop-out time                                : 12.00 

Sample size and output:
  Direction upper                              : FALSE 
  median(1)                                    : 80.0 
  median(2)                                    : 60.0 
  lambda(1)                                    : 0.00866 
  Maximum number of subjects (1)               : 600 
  Maximum number of subjects (2)               : 600 
  Maximum number of events                     : 407.7 
  Follow up time                               : 29.62 
  Reject per stage [1]                         : 0.000154 
  Reject per stage [2]                         : 0.433149 
  Reject per stage [3]                         : 0.366697 
  Overall futility stop                        : 0.05582 
  Futility stop per stage [1]                  : 0.05582 
  Futility stop per stage [2]                  : 0.00000 
  Early stop                                   : 0.4891 
  Analysis times [1]                           : 25.26 
  Analysis times [2]                           : 40.65 
  Analysis times [3]                           : 58.19 
  Expected study duration                      : 48.75 
  Maximal study duration                       : 58.19 
  Number of events per stage [1]               : 122.3 
  Number of events per stage [2]               : 269.1 
  Number of events per stage [3]               : 407.7 
  Expected number of events under H0           : 264.2 
  Expected number of events under H0/H1        : 334.6 
  Expected number of events under H1           : 331.7 
  Number of subjects [1]                       : 1060.9 
  Number of subjects [2]                       : 1200 
  Number of subjects [3]                       : 1200 
  Expected number of subjects under H1         : 1192.2 
  Critical values (treatment effect scale) [1] : 0.391 
  Critical values (treatment effect scale) [2] : 0.735 
  Critical values (treatment effect scale) [3] : 0.821 
  Futility bounds (treatment effect scale) [1] : 1.000 
  Futility bounds (treatment effect scale) [2] : NA 
  Futility bounds (one-sided p-value scale) [1] : 0.5000 
  Futility bounds (one-sided p-value scale) [2] : 1.0000 

Legend:
  (i): values of treatment arm i
  [k]: values at stage k</code></pre>
</div>
</div>
<p>So adding these interims (and not accounting for the power loss induced through adding the futility!) increases the number of events from 380 to 408 - only a slight increase.</p>
<p>Note that at the second interim stopping for futility is not foreseen anymore (the <code>-6</code> for <code>futilityBounds</code> enforces that).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># information fractions after which to perform interim looks</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>nevents_i1 <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(info <span class="sc">*</span> samplesize<span class="sc">$</span>maxNumberOfEvents)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>nevents_i1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 123 270 408</code></pre>
</div>
</div>
<p>Now the key is that when using a group-sequential design, or say if we run 100 of them, some of them will actually stop at the first or second interim. We can compute the probabilities for that happening as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># stopping probabilities at futility and efficacy interim under H0 and H1</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>designChar <span class="ot">&lt;-</span> <span class="fu">getDesignCharacteristics</span>(design)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>stopProbsH0 <span class="ot">&lt;-</span> <span class="fu">getPowerAndAverageSampleNumber</span>(design, <span class="at">theta =</span> <span class="dv">0</span>, <span class="at">nMax =</span> designChar<span class="sc">$</span>shift)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>stopProbsH1 <span class="ot">&lt;-</span> <span class="fu">getPowerAndAverageSampleNumber</span>(design, <span class="at">theta =</span> <span class="dv">1</span>, <span class="at">nMax =</span> designChar<span class="sc">$</span>shift)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>stopFutIA_H0 <span class="ot">&lt;-</span> stopProbsH0<span class="sc">$</span>earlyStop[<span class="st">"stage = 1"</span>, <span class="dv">1</span>]</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>stopEffIA_H0 <span class="ot">&lt;-</span> stopProbsH0<span class="sc">$</span>earlyStop[<span class="st">"stage = 2"</span>, <span class="dv">1</span>]</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>stopFutIA_H1 <span class="ot">&lt;-</span> stopProbsH1<span class="sc">$</span>earlyStop[<span class="st">"stage = 1"</span>, <span class="dv">1</span>]</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>stopEffIA_H1 <span class="ot">&lt;-</span> stopProbsH1<span class="sc">$</span>earlyStop[<span class="st">"stage = 2"</span>, <span class="dv">1</span>]</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># probability to stop at the futility interim, under H0 and H1</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(stopFutIA_H0, stopFutIA_H1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stage = 1 stage = 1 
0.5000001 0.0559722 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability to stop at the efficacy interim, under H0 and H1</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(stopEffIA_H0, stopEffIA_H1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stage = 2 stage = 2 
0.0057649 0.4331487 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected number of events under H0 and H1 </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>expH0 <span class="ot">&lt;-</span> samplesize<span class="sc">$</span>expectedEventsH0</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>expH1 <span class="ot">&lt;-</span> samplesize<span class="sc">$</span>expectedEventsH1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now the point is that if we stop at an interim we will need less events, because we would stop the trial then. The <strong>expected number of events</strong> can be computed as follows:</p>
<ul>
<li>Under <span class="math inline">\(H_0\)</span>: 0.500 <span class="math inline">\(\cdot\)</span> 123 + 0.006 <span class="math inline">\(\cdot\)</span> 270 + 0.494 <span class="math inline">\(\cdot\)</span> 408 = 264.</li>
<li>Under <span class="math inline">\(H_1\)</span>: 0.056 <span class="math inline">\(\cdot\)</span> 123 + 0.433 <span class="math inline">\(\cdot\)</span> 270 + 0.511 <span class="math inline">\(\cdot\)</span> 408 = 332.</li>
</ul>
<p>So if we use the specified group-sequential design and in fact, our intervention does not work at all (<span class="math inline">\(H_0\)</span> is true), then on average we only need 264 instead of the 380 events in a single-stage design.</p>
<p>Under <span class="math inline">\(H_1\)</span>, i.e.&nbsp;if the drug works as assumed for powering the trial, we then need on average only 332 events to show that, i.e.&nbsp;reject the null hypothesis of the hazard ratio being equal to 0. This is the point of group-sequential designs: the maximal number of events in a given trial is slightly increased, but the average number of events over a portfolio of trials is reduced.</p>
<p>Now, what effect size do we need to observe at the efficacy interim to stop the trial, based on an O’Brien-Fleming <span class="math inline">\(\alpha\)</span>-spending function? We can easily extract that number from the above output as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># critical values on effect, i.e. hazard ratio, scale</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>crit1 <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">disp</span>(samplesize<span class="sc">$</span>criticalValuesEffectScale, <span class="dv">3</span>))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>crit1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]    [,2]    [,3]   
[1,] "0.391" "0.735" "0.821"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2-sided significance levels on p-value scale</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>crit2 <span class="ot">&lt;-</span> <span class="fu">disp</span>(samplesize<span class="sc">$</span>criticalValuesPValueScale <span class="sc">*</span> <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>crit2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "0.0000002" "0.012"     "0.046"    </code></pre>
</div>
</div>
<p>So this means that after 66% of events, in order to get a <span class="math inline">\(p\)</span>-value below the pre-specified boundary of 0.012 the hazard ratio must be below 0.735. The latter is what sometimes is called <strong>minimal detectable difference</strong>, MDD. Two observations can be made from that:</p>
<ul>
<li>Often, people believe in order to stop a trial early the effect seen at the interim must be <strong>much larger</strong> than what we assumed for powering. Comparing 0.75 to 0.735 it is clear that this is not the case. That the MDD at interim and the effect we power at are approximately the same is typically the case for an O’Brien-Fleming boundary and an interim after about 2/3 of information.</li>
<li>Another common belief is that in order to be significant at the interim we need to observe a hazard ratio <span class="math inline">\(\le 0.75\)</span>. Again, this is not true: the MDD at the final analysis actually is 0.821, i.e.&nbsp;in order to get a <span class="math inline">\(p\)</span>-value of 0.046 or lower this is the hazard ratio we need to beat.</li>
</ul>
</section>
<section id="inference-after-early-stopping" class="level1">
<h1>Inference after early stopping</h1>
<p>See this <a href="https://vignettes.rpact.org/html/rpact_analysis_examples.html">rpact vignette</a> for further details.</p>
<section id="conventional-analyses-at-the-first-and-second-interim-analysis" class="level2">
<h2 class="anchored" data-anchor-id="conventional-analyses-at-the-first-and-second-interim-analysis">Conventional analyses at the first and second interim analysis</h2>
<p>Assume the following results from standard inference at the <strong>futility interim analysis performed after 123 events</strong> have been observed:</p>
<ul>
<li>Stratified HR 0.69 (95% CI 0.47 to 1.01). <span class="math inline">\(\Rightarrow\)</span> this was <span class="math inline">\(\le 1\)</span>, so <strong>trial continues.</strong></li>
<li>log(HR) = log(0.69) with standard error 0.20.</li>
<li>Corresponding Z-score: log(0.69)/0.20 = -1.86.</li>
</ul>
<p>Results from standard inference at the <strong>efficacy interim analysis after 270 events</strong>:</p>
<ul>
<li>Stratified HR 0.66 (95% CI 0.51 to 0.85).</li>
<li>log(HR) = log(0.66) with standard error 0.13.</li>
<li>Corresponding Z-score: log(0.66)/0.13 = -3.225.</li>
<li>Two-sided p-value is 0.0012 which was smaller than the critical value from the O’Brien-Fleming boundary of 0.012. <span class="math inline">\(\Rightarrow\)</span> <strong>Trial stopped early for efficacy</strong>.</li>
</ul>
</section>
<section id="analysis-accounting-for-the-group-sequential-design" class="level2">
<h2 class="anchored" data-anchor-id="analysis-accounting-for-the-group-sequential-design">Analysis accounting for the group-sequential design</h2>
<p>The <strong>results after the first and second interim</strong> are specified using the function <code>getDataset</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># overallLogRanks: One-sided logrank statistic or Z-score (= log(HR) / SE) from Cox regression</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">getDataset</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">overallEvents =</span> nevents_i1[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">overallLogRanks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.86</span>, <span class="sc">-</span><span class="fl">3.225</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">overallAllocationRatio =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, this is used for creating the <strong>adjusted inference</strong> using the function <code>getAnalysisResults</code> (<code>directionUpper = FALSE</code> is specified because the power is directed towards negative values of the logrank statistics):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>adj_result <span class="ot">&lt;-</span> <span class="fu">getAnalysisResults</span>(<span class="at">design =</span> design, </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">dataInput =</span> results, <span class="at">stage =</span> <span class="dv">2</span>, <span class="at">directionUpper =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[PROGRESS] Stage results calculated [0.0436 secs] 
[PROGRESS] Conditional power calculated [0.0442 secs] 
[PROGRESS] Conditional rejection probabilities (CRP) calculated [0.0014 secs] 
[PROGRESS] Repeated confidence interval of stage 1 calculated [0.9783 secs] 
[PROGRESS] Repeated confidence interval of stage 2 calculated [0.7699 secs] 
[PROGRESS] Repeated confidence interval calculated [1.75 secs] </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Repeated p-values not available for 'typeOfDesign' = 'asUser'</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[PROGRESS] Repeated p-values calculated [0.0012 secs] 
[PROGRESS] Final p-value calculated [0.0021 secs] 
[PROGRESS] Final confidence interval calculated [0.0919 secs] </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>adj_result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis results (survival of 2 groups, group sequential design):

Design parameters:
  Information rates                            : 0.300, 0.660, 1.000 
  Critical values                              : 5.199, 2.524, 1.992 
  Futility bounds (non-binding)                : 0.000, -Inf 
  Cumulative alpha spending                    : 0.0000001, 0.0057983, 0.0250000 
  Local one-sided significance levels          : 0.0000001, 0.0057983, 0.0232097 
  Significance level                           : 0.0250 
  Test                                         : one-sided 

User defined parameters:
  Direction upper                              : FALSE 

Default parameters:
  Normal approximation                         : TRUE 
  Theta H0                                     : 1 

Stage results:
  Cumulative effect sizes                      : 0.7150, 0.6753, NA 
  Stage-wise test statistics                   : -1.860, -2.669, NA 
  Stage-wise p-values                          : 0.03144, 0.00380, NA 
  Overall test statistics                      : -1.860, -3.225, NA 
  Overall p-values                             : 0.0314428, 0.0006299, NA 

Analysis results:
  Actions                                      : continue, reject and stop, NA 
  Conditional rejection probability            : 0.1359, 0.8594, NA 
  Conditional power                            : NA, NA, NA 
  Repeated confidence intervals (lower)        : 0.2800, 0.4967, NA 
  Repeated confidence intervals (upper)        : 1.8261, 0.9182, NA 
  Repeated p-values                            : NA, NA, NA 
  Final stage                                  : 2 
  Final p-value                                : NA, 0.0006299, NA 
  Final CIs (lower)                            : NA, 0.532, NA 
  Final CIs (upper)                            : NA, 0.8573, NA 
  Median unbiased estimate                     : NA, 0.6753, NA </code></pre>
</div>
</div>
<p>The output is explained as follows:</p>
<ul>
<li><code>Critical values</code> are group-sequential efficacy boundary values on the <span class="math inline">\(Z\)</span>-scale, <code>stage levels</code> are the corresponding one-sided local significance levels.</li>
<li><code>Effect sizes</code>, <code>Test statistics</code>, and <code>p-values</code> refer to hazard ratio estimates, <span class="math inline">\(Z\)</span>-scores, and <span class="math inline">\(p\)</span>-values obtained from the first interim analysis and results which would have been obtained after the second interim analysis if not all data up to the second interim analysis but only new data since the first interim had been included (i.e., per-stage results).</li>
<li><code>Overall test statistics</code> are the given (overall, not per-stage) <span class="math inline">\(Z\)</span>-scores from each interim and <code>Overall p-value</code> the corresponding one-sided <span class="math inline">\(p\)</span>-values.</li>
<li><code>RCIs</code> are repeated confidence intervals which provide valid (but conservative) inference at any stage of an ongoing or stopped group-sequential trial. <code>Repeated p-values</code> are the corresponding <span class="math inline">\(p\)</span>-values.</li>
<li><code>Final p-value</code> is the <strong>final one-sided adjusted <span class="math inline">\(p\)</span>-value</strong> based on the stagewise ordering of the sample space.</li>
<li><code>Median unbiased estimate</code> and <code>Final CIs</code> are the corresponding <strong>adjusted treatment effect estimate</strong> and the <strong>confidence interval</strong> for the hazard ratio at the interim analysis where the trial was stopped.</li>
</ul>
<p>Note that for this example, the <strong>adjusted final hazard ratio of 0.68 and the adjusted confidence interval of (0.53, 0.86) match the results from the conventional analysis almost exactly for the first two decimals.</strong></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>